
build_list = idodVR alaw2mp3
clean_list = *.o $(build_list)

include ../Makefile.inc

# --------------------------

idodVR: idodVR.o

idodVR.o: idodVR.cpp ../c54setp/c54setp.h


alaw2mp3: alaw2mp3.o

alaw2mp3.o: alaw2mp3.cpp

